import type { Metadata } from "next"
import type { ReactNode } from "react"

import { TooltipProvider } from "@/components/ui/tooltip"

import "./globals.css"

export const metadata: Metadata = {
  title: "AnyDesign React Project",
  description: "A visual-first React project generated by AnyDesign Runtime.",
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <TooltipProvider>
          <div className="isolate min-h-svh">{children}</div>
        </TooltipProvider>
      </body>
    </html>
  )
}
