spec:
  template:
    spec:
      containers:
        - name: runtime
          volumeMounts:
            - name: release-packaging-proxy
              mountPath: /opt/anydesign/release-packaging-proxy-helper.mjs
              subPath: release-packaging-proxy-helper.mjs
              readOnly: true
            - name: release-packaging-proxy-token
              mountPath: /var/run/anydesign/release-packager
              readOnly: true
      volumes:
        - name: release-packaging-proxy
          configMap:
            name: release-packaging-proxy
            defaultMode: 365
        - name: release-packaging-proxy-token
          secret:
            secretName: release-packaging-proxy-token
            defaultMode: 292
