apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxWarmPool
metadata:
  name: anydesign-next-app-pool
  namespace: anydesign-sandboxes
spec:
  replicas: 0
  sandboxTemplateRef:
    name: anydesign-next-app
